# Generated by Django 2.2.3 on 2019-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date_published'),
        ),
    ]
