# Generated by Django 2.2.3 on 2019-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='memo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
