# Generated by Django 2.2.3 on 2019-07-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_bookmark_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_published'),
        ),
    ]
